services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=cidadaodeolho
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: bash -c "php artisan migrate && php artisan app:sync-deputados-em-exercicio && php artisan app:sync-redes-sociais && php artisan app:sync-verbas-indenizatorias && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vue-app
    container_name: vue
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cidadaodeolho
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: